# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='ProtoMessage.proto',
  package='SpyClient',
  serialized_pb='\n\x12ProtoMessage.proto\x12\tSpyClient\"\xc7\x01\n\x08IpPacket\x12*\n\x0cprotocoltype\x18\x01 \x02(\x0e\x32\x14.SpyClient.PhoneType\x12\x0b\n\x03sip\x18\x02 \x02(\t\x12\x0b\n\x03\x64ip\x18\x03 \x02(\t\x12\r\n\x05sport\x18\x04 \x02(\x05\x12\r\n\x05\x64port\x18\x05 \x02(\x05\x12\x0c\n\x04\x66low\x18\x06 \x02(\x05\x12\x10\n\x08\x64\x61tetime\x18\x07 \x02(\t\x12\x0e\n\x06length\x18\x08 \x02(\x05\x12\x13\n\x0bprocessname\x18\t \x01(\t\x12\x12\n\nprocessmd5\x18\n \x01(\t\"\x90\x01\n\nHttpPacket\x12\x0b\n\x03sip\x18\x01 \x02(\t\x12\x0b\n\x03\x64ip\x18\x02 \x02(\t\x12\r\n\x05sport\x18\x03 \x02(\x05\x12\r\n\x05\x64port\x18\x04 \x02(\x05\x12\x0f\n\x07httpurl\x18\x05 \x02(\t\x12\x10\n\x08\x64\x61tetime\x18\x06 \x02(\t\x12\x13\n\x0bprocessname\x18\x07 \x01(\t\x12\x12\n\nprocessmd5\x18\x08 \x01(\t\"\xe7\x01\n\x0b\x45mailPacket\x12\x0b\n\x03sip\x18\x01 \x02(\t\x12\x0b\n\x03\x64ip\x18\x02 \x02(\t\x12\r\n\x05sport\x18\x03 \x02(\x05\x12\r\n\x05\x64port\x18\x04 \x02(\x05\x12\x0e\n\x06sendto\x18\x05 \x02(\t\x12\x0e\n\x06sendcc\x18\x06 \x01(\t\x12\x0f\n\x07sendbcc\x18\x07 \x01(\t\x12\x10\n\x08sendfrom\x18\x08 \x02(\t\x12\x0f\n\x07subject\x18\t \x01(\t\x12\x10\n\x08\x64\x61tetime\x18\n \x02(\t\x12\x11\n\temailtype\x18\x0b \x02(\x05\x12\x13\n\x0bprocessname\x18\x0c \x01(\t\x12\x12\n\nprocessmd5\x18\r \x01(\t\"Y\n\x0cWhiteProcess\x12\x13\n\x0bprocessname\x18\x01 \x02(\t\x12\x0f\n\x07version\x18\x02 \x02(\t\x12\x12\n\nprocessmd5\x18\x03 \x02(\t\x12\x0f\n\x07\x61\x64\x64time\x18\x04 \x02(\t\"\x1a\n\x0cTrojanPacket\x12\n\n\x02id\x18\x02 \x02(\x05*/\n\tPhoneType\x12\x10\n\x0cTCP_PROTOCOL\x10\x00\x12\x10\n\x0cUDP_PROTOCOL\x10\x01')

_PHONETYPE = descriptor.EnumDescriptor(
  name='PhoneType',
  full_name='SpyClient.PhoneType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='TCP_PROTOCOL', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UDP_PROTOCOL', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=735,
  serialized_end=782,
)


TCP_PROTOCOL = 0
UDP_PROTOCOL = 1



_IPPACKET = descriptor.Descriptor(
  name='IpPacket',
  full_name='SpyClient.IpPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='protocoltype', full_name='SpyClient.IpPacket.protocoltype', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sip', full_name='SpyClient.IpPacket.sip', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dip', full_name='SpyClient.IpPacket.dip', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sport', full_name='SpyClient.IpPacket.sport', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dport', full_name='SpyClient.IpPacket.dport', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flow', full_name='SpyClient.IpPacket.flow', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='datetime', full_name='SpyClient.IpPacket.datetime', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='length', full_name='SpyClient.IpPacket.length', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='processname', full_name='SpyClient.IpPacket.processname', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='processmd5', full_name='SpyClient.IpPacket.processmd5', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=233,
)


_HTTPPACKET = descriptor.Descriptor(
  name='HttpPacket',
  full_name='SpyClient.HttpPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sip', full_name='SpyClient.HttpPacket.sip', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dip', full_name='SpyClient.HttpPacket.dip', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sport', full_name='SpyClient.HttpPacket.sport', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dport', full_name='SpyClient.HttpPacket.dport', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='httpurl', full_name='SpyClient.HttpPacket.httpurl', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='datetime', full_name='SpyClient.HttpPacket.datetime', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='processname', full_name='SpyClient.HttpPacket.processname', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='processmd5', full_name='SpyClient.HttpPacket.processmd5', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=236,
  serialized_end=380,
)


_EMAILPACKET = descriptor.Descriptor(
  name='EmailPacket',
  full_name='SpyClient.EmailPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sip', full_name='SpyClient.EmailPacket.sip', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dip', full_name='SpyClient.EmailPacket.dip', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sport', full_name='SpyClient.EmailPacket.sport', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dport', full_name='SpyClient.EmailPacket.dport', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sendto', full_name='SpyClient.EmailPacket.sendto', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sendcc', full_name='SpyClient.EmailPacket.sendcc', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sendbcc', full_name='SpyClient.EmailPacket.sendbcc', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sendfrom', full_name='SpyClient.EmailPacket.sendfrom', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='subject', full_name='SpyClient.EmailPacket.subject', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='datetime', full_name='SpyClient.EmailPacket.datetime', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='emailtype', full_name='SpyClient.EmailPacket.emailtype', index=10,
      number=11, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='processname', full_name='SpyClient.EmailPacket.processname', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='processmd5', full_name='SpyClient.EmailPacket.processmd5', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=383,
  serialized_end=614,
)


_WHITEPROCESS = descriptor.Descriptor(
  name='WhiteProcess',
  full_name='SpyClient.WhiteProcess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='processname', full_name='SpyClient.WhiteProcess.processname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='version', full_name='SpyClient.WhiteProcess.version', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='processmd5', full_name='SpyClient.WhiteProcess.processmd5', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='addtime', full_name='SpyClient.WhiteProcess.addtime', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=616,
  serialized_end=705,
)


_TROJANPACKET = descriptor.Descriptor(
  name='TrojanPacket',
  full_name='SpyClient.TrojanPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='SpyClient.TrojanPacket.id', index=0,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=707,
  serialized_end=733,
)

_IPPACKET.fields_by_name['protocoltype'].enum_type = _PHONETYPE
DESCRIPTOR.message_types_by_name['IpPacket'] = _IPPACKET
DESCRIPTOR.message_types_by_name['HttpPacket'] = _HTTPPACKET
DESCRIPTOR.message_types_by_name['EmailPacket'] = _EMAILPACKET
DESCRIPTOR.message_types_by_name['WhiteProcess'] = _WHITEPROCESS
DESCRIPTOR.message_types_by_name['TrojanPacket'] = _TROJANPACKET

class IpPacket(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _IPPACKET
  
  # @@protoc_insertion_point(class_scope:SpyClient.IpPacket)

class HttpPacket(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HTTPPACKET
  
  # @@protoc_insertion_point(class_scope:SpyClient.HttpPacket)

class EmailPacket(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EMAILPACKET
  
  # @@protoc_insertion_point(class_scope:SpyClient.EmailPacket)

class WhiteProcess(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WHITEPROCESS
  
  # @@protoc_insertion_point(class_scope:SpyClient.WhiteProcess)

class TrojanPacket(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TROJANPACKET
  
  # @@protoc_insertion_point(class_scope:SpyClient.TrojanPacket)

# @@protoc_insertion_point(module_scope)
